### ISSUE TITLE
Jest error when using react-native-picker-select

### ISSUE THREAD

**Issue by sandberg75** [lawnstarter/react-native-picker-select#438]
Hi, I have just started to try to write some tests using Jest, but my tests complains,
`  ● Test suite failed to run

    TypeError: (0 , _reactNative.requireNativeComponent) is not a function

      at Object.<anonymous> (node_modules/react-native-picker-select/node_modules/@react-native-community/picker/js/RNCPickerNativeComponent.js:45:20)
      at Object.<anonymous> (node_modules/react-native-picker-select/node_modules/@react-native-community/picker/js/PickerIOS.ios.js:18:1)
`
Any idea how I can resolve this? I have tried to mock it but without success.

**Comment by lfkwtz** [comment]
@sandberg75 this issue was automatically closed because it did not follow one of the available issue templates. See [here](https://github.com/lawnstarter/react-native-picker-select/issues/new/choose) for available options.
